### ISSUE TITLE
Better Commit Messages

### ISSUE THREAD

**Issue by dbarabander** [Gerzer/Locomotive#1]
Gabe, you need to make these commit messages useful.

**Comment by Gerzer** [comment]
Yup :)

**Comment by dbarabander** [comment]
Also, there should be a sole commit to remove the duplicate xcworkspace's. Locomotive.xcworkspace isn't in there and it screwed Emma up. So I would delete the old Jared one's, pod install, and push so everyone can be on the same page. Otherwise you're going to have ridiculous merge conflicts.

Other than that keep it up, you're an Ace.

**Comment by Gerzer** [comment]
OK, I am almost done simplifying the duplicates crisis. Pods should work just fine once I push up the latest changes.
